### PR TITLE
add two regression metrics and two ranking metrics

### PR DESCRIPTION
**Pull request by travisbrady**
Wanted to get learn some rustlearn and Rust more generally so I added:

- dcg_score
- ndcg_score
- mean absolute error
- mean squared error

One note, `cargo test` fails for me on something unrelated with:
```
failures:

---- factorization::factorization_machines::tests::test_iris_parallel stdout ----
	Accuracy 0.7
Train accuracy 0.7
thread 'factorization::factorization_machines::tests::test_iris_parallel' panicked at 'assertion failed: test_accuracy > 0.94', src/factorization/factorization_machines.rs:637


failures:
    factorization::factorization_machines::tests::test_iris_parallel

test result: FAILED. 68 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

### CODE REVIEW

**Comment by maciejkula** [comment]
Great! Could you push again (you can do `git commit --amend` and `git push --force`) to trigger a CI build?

**Comment by travisbrady** [comment]
@maciejkula Certainly. Just pushed.

**Comment by maciejkula** [comment]
Cool, looks great! I don't know why you were getting failures locally, CI seems to pass just fine!

**Comment by travisbrady** [comment]
@maciejkula Anything else necessary to merge?

**Comment by maciejkula** [comment]
No, looks great. I'll merge when I'm at a computer.

**Comment by travisbrady** [comment]
Excellent. By the way, any wishlist algorithms or features you've wanted to implement? I'd like to try my hand at more here.

**Comment by maciejkula** [comment]
That would be great! I can come back to you with some a more thought-out list, but here's a couple of things off the top of my head:
- change serialization to `serde`;
- change dense matrices to `ndarray` (this would be a _huge_ change)
- add a kNN classifier

**Pull request merged**
