### PR TITLE
Fix EncodableRng JSON serialization.

### LINKED ISSUE #31: Unable to deserialize Random Forest model
After fitting a model I serialize it to the disk using rustc_serialize json.

I then try to load the model but I get a parse error. The reason is that the 'rng' field of the model looks like this:

... ,"feature_types":[],"rng":},{"dim":4 ...

That is, some normal fields, then the rng field, a colon, and nothing - the object just closes.

Using rustc_serialize = "0.3.*"

rustc -V
rustc 1.13.0-nightly (3c5a0fa45 2016-08-22)

The following functions are used to load and store the random forest.

```
pub fn serialize_to_file<T>(s: &T, path: &str)
    where T: Encodable
{
    let serialized = json::encode(&s).unwrap();

    let mut f = File::create(path).unwrap();
    write!(f, "{}", serialized).unwrap();
    f.flush().unwrap();
}

pub fn load_json<T: Decodable>(path: &str) -> T {
    let mut f = File::open(path).unwrap();
    let mut json_str = String::new();

    let _ = f.read_to_string(&mut json_str).unwrap();
    json::decode(&json_str).unwrap()
}
```

### PR DESCRIPTION
**Pull request by maciejkula**
Fixes #31

### CODE REVIEW

**Comment by insanitybit** [comment]
This did fix #31 but deserializing now fails with:

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: MissingFieldError("trees")', ../src/libcore/result.rs:788

I do see a 'trees' field in my json, however it is a subobject of the "basemodel" field. There is another "trees" field in a list in the "models" object.

Let me know if you need more information, and thanks for the quick turnaround on the bugs so far.

**Comment by maciejkula** [comment]
Thanks for the report, I'll look into it today. If you're ok with a
workaround you could use bincode for binary serialisation in the meantime.

**Comment by insanitybit** [comment]
Thanks, that's an acceptable workaround and I'll give that a try.

**Comment by insanitybit** [comment]
Hm. So I can deserialize a model that I've fit to data. However, when I try to predict usign a deserialized model it says that I need to fit before I can predict. I had assumed that by fitting before I could load it up and start using it elsewhere.

**Comment by maciejkula** [comment]
Hmm. I really don't know what's wrong, for `bincode` I've always had serialization and deserialization tests: https://github.com/maciejkula/rustlearn/blob/master/src/ensemble/random_forest.rs#L418

**Comment by maciejkula** [comment]
Could you try to reproduce the issue on one of the built-in rustlearn datasets and post a gist? I can then get to the bottom of this.

**Comment by insanitybit** [comment]
Sure thing - I wanted to just check that the desired behavior was what I expected, a serialized model that has been fitted to data should deserialize and be able to make predictions. I'll see if I can debug / get more info to you.

**Pull request merged**
